### PR TITLE
Update Lightbend Banner

### PR DESCRIPTION
**Pull request by rasummer**
@ennru @patriknw The updated Lightbend banner for the main akka.io website. We are ready to now deploy.

akka-website

### CODE REVIEW

**Comment by ennru** [comment]
Chrome and Safari look as your screen dump.

But when I try it in Firefox 74.0 on MacOS it looks different...
image
image

**Comment by raboof** [comment]
Interesting, it seems to work for me on Firefox 74.0 (64-bit) on Linux...

**Comment by raboof** [comment]
(the gradient looks pretty neat btw)

**Comment by ennru** [comment]
Ah, we've been here before ofc.
The EFF Privacy Badger dislikes that the images come from download.lightbend.com

image

Can we package them together with this?

**Comment by rasummer** [comment]
@ennru updated to now use images stored on the akka.io domain.

**Comment by ignasi35** [comment]
Related to https://github.com/lagom/lagom.github.io/pull/222

**Pull request merged**
