### PR TITLE
Rasummer/frontend updates

### PR DESCRIPTION
**Pull request by rasummer**
@pvlugter I was hoping you can help with a couple of PRs, or know the right person. 

This updates the Lightbend banner strip at the top of the pages, as well as updates parts of the akka.io homepage. The changes have been worked on and reviewed/approved by Jonas/Jeremy/Oliver. I will also send over an akka-paradox update for the docs theme. 

Below is a screen grab of the changes, which include updated top banner, additional buttons, Lightbend section, updated users/customer logos : 

screenshot-localhost_4000-2021 07 21-11_26_55

### CODE REVIEW

**Review by pvlugter — APPROVED** [review]
LGTM

**Review by octonato — APPROVED** [review]
LGTM, not merging yet because that will immediately publish the content. 
Not that I don't think we should. I just want to make sure this is the goal. 

@rasummer let us know when this should go online, please.

**Comment by rasummer** [comment]
> LGTM, not merging yet because that will immediately publish the content.
> Not that I don't think we should. I just want to make sure this is the goal.
> 
> @rasummer let us know when this should go online, please.

As soon as you can please

**Comment by octonato** [comment]
Done! Thanks @rasummer

**Comment by rasummer** [comment]
Thanks, I'm seeing a caching issue with the css, going to send another PR that should cache bust it.

**Pull request merged**
