### PR TITLE
Add Akka Projections to the docs overview page

### PR DESCRIPTION
**Pull request by nitikagarw**
References #749

### CODE REVIEW

**Review by raboof — APPROVED** [review]

**Review by ignasi35 — CHANGES_REQUESTED** [review]
The change replaces `enhancements` with `projections`, but I think the location of `akka projections` is not correct.

In https://github.com/akka/akka.io/issues/749#issuecomment-735667034, the agreement was to add it immediately after `akka persistence`.

**Comment by nitikagarw** [comment]
Hi @ignasi35 , 
So it should look like below ?

Akka Persistence    | Akka Projections  |  Alpakka
--- | --- | --- 
Alpakka Kafka | Akka gRPC | Akka Management

**Comment by ignasi35** [comment]
Yeah, that was my understanding. WDYT @patriknw ?

**Comment by patriknw** [comment]
Yes, that was my suggestion. Projections is related to Persistence.

While we are at it we can make both Alpakkas on the same row.

Akka Persistence    | Akka Projections  |  Akka Management
--- | --- | --- 
**Alpakka** | **Alpakka Kafka** | **Akka gRPC**

**Review by ignasi35 — APPROVED** [review]

**Comment by ignasi35** [comment]
Brilliant! Thanks @nitikagarw 🙇🏼‍♂️

**Pull request merged**
