### PR TITLE
Remove old google analytics universal - no longer processing data

### PR DESCRIPTION
**Pull request by rasummer**
@ennru or @johanandren 

I've removed the old Google Universal Analytics script as it no longer processes data. 

We currently use Google Tag Manager to send data from Akka.io to our Google Analytics 4 Property. 

If you have access to the old Akka Google Universal Analytics Property, namely UA-21117439-1, then you can go there and download our old data for archival purposes.

### CODE REVIEW

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by johanandren** [comment]
No need to drop the same in Akka-paradox theme and/or already published docs?

**Comment by rasummer** [comment]
> No need to drop the same in Akka-paradox theme and/or already published docs?

We removed it a little while back from the paradox theme: https://github.com/akka/akka-paradox/pull/203/files

**Comment by johanandren** [comment]
Thanks, I did it but didn't remember that :D

**Pull request merged**
