### PR TITLE
News Banner - Added Akka Insights, removed Akka Cloud Platform

### PR DESCRIPTION
**Pull request by rasummer**
@ennru This swaps out the news banner promo at the top of the page. Adding Akka Insights and removing Akka Cloud Platform.

### CODE REVIEW

**Comment by rasummer** [comment]
@ennru look like some of the checks are waiting, neither a fail or success. Not sure who would be best to take a look at these?

**Comment by ennru** [comment]
They didn't trigger. Can you try and push an unimportant change?

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by rasummer** [comment]
Thanks Enno, assuming it auto deploys?

**Comment by rasummer** [comment]
Never mind, it just went live :)

**Comment by ennru** [comment]
Yes. It is updated.

**Pull request merged**
