### PR TITLE
update akka homepage

### PR DESCRIPTION
**Pull request by rasummer**
@ennru 

Here are the updates to the Akka.io homepage.

We now have one main message at the top in the hero (more messaging tweaks to come over time).  The  5 icons and bullets are now moved below the blue header as to not compete with the one main message. The BSL messaging that was in the blue header is now at the bottom. 

image

Because we removed the Akka Edge messaging from the blue header, so it doesn't compete with the main message, I've added an Akka Edge section to the Try Akka page. I did this as the main CTA button in the homepage hero sends you to Try Akka. For this section I just reused the text you already use for the Edge listing in the docs page.  I'm sure over time we will likely bring Akka Edge back into the homepage, but wanted to get these changes up and out. 

image

I did some clean up on the Get Involved page as the grid of boxes were unevenly spaced out. I also cleaned up the inline SVGs in this page. 

image

Lastly I've updated the main background image that is used in the hero header, footer etc with an SVG. I needed a different image now that the homepage header text isn't two columns. Also It now looks crisper as the old one had noise in it. Probably due to JPEG compression.

### CODE REVIEW

**Comment by johanandren** [comment]
@rasummer one bit of feedback I got from talking to the guy who did the original design, the other day, was that we should remove the box drop shadows because it looks dated :)

**Comment by johanandren** [comment]
Changes looks good to me, BTW 👍

**Comment by rasummer** [comment]
> @rasummer one bit of feedback I got from talking to the guy who did the original design, the other day, was that we should remove the box drop shadows because it looks dated :)

@johanandren I can look into this and make some updates in a future PR.

**Comment by rasummer** [comment]
@johanandren looks like Enno is out of office today, could you approve and deploy? This has been approved by leadership.

**Review by johanandren — APPROVED** [review]

**Comment by rasummer** [comment]
@johanandren  I notice that the site sometimes loads with the main blue hero background image, other times it doesn't. Do you think it could have something to do with the following deploy actions message: [publish](https://github.com/akka/akka.io/actions/runs/7846307237/job/21412691232)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.1.0, actions/cache@v3.2.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by rasummer** [comment]
See https://github.com/akka/akka.io/actions/runs/7846307237

**Comment by johanandren** [comment]
I don't think that is the reason, that's just something we'll have to upgrade soonish but that works for now. Could it be something with things not reaching the CDN? I see the changed bg consistently on all akka.io pages.

**Comment by rasummer** [comment]
Yep, going to push something right now that should help with the CSS file and cache

**Pull request merged**
